"""add_summary_and_key_points

Revision ID: e86ac1a71500
Revises: 475b01287eb4
Create Date: 2026-06-02 15:34:12.746739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e86ac1a71500'
down_revision: Union[str, Sequence[str], None] = '475b01287eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('chunks', sa.Column('key_points', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'key_points')
    op.drop_column('chunks', 'summary')
    # ### end Alembic commands ###
